### ISSUE TITLE
Add licence to the table

### ISSUE THREAD

**Issue by ftyers** [JRMeyer/open-speech-corpora#3]
:D

**Comment by JRMeyer** [comment]
Which license?

**Comment by ftyers** [comment]
The licence of each of the corpora.

**Comment by ftyers** [comment]
Looks like it's done :)

**Comment by JRMeyer** [comment]
I will put up corpora before I know their exact license, and in that case feel free to send a PR if you know it:)

I put up the 19k hour fearless corpus, because I know it's OK for research. However, the exact license I don't know yet. I sent them an email already:)
